name: Difference CI
 
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # https://github.com/actions/checkout#Checkout-multiple-repos-private
    # problem, bo moze byc inny basebranch  
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x

    - name: Setup cache key and directory for gems cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-use-ruby-${{ hashFiles('**/Gemfile.lock') }}

    - name: Checkout chess repo
      uses: actions/checkout@v2
      with:
        repository: Boberkraft/chess
        path: chess

      # Find the PR associated with this push, if there is one.
    - uses: jwalton/gh-find-current-pr@v1
      id: findPr
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      # This will echo "Your PR is 7", or be skipped if there is no current PR.
    - run: echo "Your PR_BODY is ${PR_BODY}"
      if: success() && steps.findPr.outputs.body
      env:
        PR_BODY: ${{ steps.findPr.outputs.body }}

    - name: Parse Pull request message
      run: |
        chmod 777 $GITHUB_WORKSPACE/lib/scripts/pull_request_parser.rb
        sudo $GITHUB_WORKSPACE/lib/scripts/pull_request_parser.rb

    - name: Change branches
      env:
        GITHUB_WORKSPACE: ${{ env.GITHUB_WORKSPACE }}
      run: |
        chmod 777 $GITHUB_WORKSPACE/lib/scripts/change_branches.rb
        sudo $GITHUB_WORKSPACE/lib/scripts/change_branches.rb


    - name: Bundler Install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        rake db:migrate RAILS_ENV=development
    - name: Testing master...
      run: bundle exec rake my_namespace:my_task1
      
    - uses: actions/checkout@v2

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x  
    - name: Install dependentices
      run: sudo apt-get install libsqlite3-dev
    - name: Bundler Install
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        rake db:migrate RAILS_ENV=development
    - name: Testing your branch....
      run: bundle exec rake my_namespace:my_task1

    - name: Create URL to the run output
      id: vars
      run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

    - name: Update comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        token: ${{ secrets.TOKEN }}
        repository: ${{ github.event.client_payload.repository }}
        comment-id: ${{ github.event.client_payload.comment_id }}
        body: |
          > ${{ github.event.client_payload.repository }} ${{ steps.vars.outputs.run-url }}





          - name: da1
            run: sudo apt-get install tree

          - name: da
            run: tree $GITHUB_WORKSPACE
          - name: da2
            run: tree $HOME
