name: Create Tests

on:
  repository_dispatch:
    types: [test-command]

jobs:
  create_many_tests:
    runs-on: self-hosted

    env:
      TOKEN: ${{ secrets.TOKEN }}
      COMMENT_ID: ${{ github.event.client_payload.github.payload.comment.id }}
      REPOSITORY_NAME: ${{ github.event.client_payload.github.payload.repository.full_name }}
      REPOSITORIES: ${{ github.event.client_payload.slash_command.args }}
      BRANCH_NAME: test-sypania
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1

      - name: Ping main repo
        run: |
          sudo -E ruby $GITHUB_WORKSPACE/lib/workflow/create_many_tests.rb
