name: Difference CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # https://github.com/actions/checkout#Checkout-multiple-repos-private
    # problem, bo moze byc inny basebranch
    steps:
    - uses: actions/checkout@v2
      
    - uses: trilom/file-changes-action@v1
      with: 
        githubToken: ${{ secrets.GITHUB_TOKEN }}  

    - uses: actions/checkout@v2
      with:
        ref: master

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x  
    - name: Install dependentices
      run: sudo apt-get install libsqlite3-dev
    - name: Bundler Install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        rake db:migrate RAILS_ENV=development

    - name: Testing master...
      run: bundle exec rake my_namespace:my_task1
      
    - uses: actions/checkout@v2

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x  
    - name: Install dependentices
      run: sudo apt-get install libsqlite3-dev
    - name: Bundler Install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        rake db:migrate RAILS_ENV=development
    - name: Testing your branch....
      run: bundle exec rake my_namespace:my_task1
