name: Difference CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    # https://github.com/actions/checkout#Checkout-multiple-repos-private
    # problem, bo moze byc inny basebranch
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x  
      
      # Find the PR associated with this push, if there is one.
    - uses: jwalton/gh-find-current-pr@v1
      id: findPr
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    # This will echo "Your PR is 7", or be skipped if there is no current PR.
    - run: echo "Your PR is ${PR}"
      if: success() && steps.findPr.outputs.number
      env:
        PR_BODY: ${{ steps.findPr.outputs.body }}
    - name: Parse Pull request message
      run: |
        $HOME/tweetster-rails-api/lib/scripts/pull_request_parser.rb
    - name: Install dependentices
      run: sudo apt-get install libsqlite3-dev
    - name: Bundler Install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        rake db:migrate RAILS_ENV=development
    - name: Testing master...
      run: bundle exec rake my_namespace:my_task1
      
    - uses: actions/checkout@v2

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.x  
    - name: Install dependentices
      run: sudo apt-get install libsqlite3-dev
    - name: Bundler Install
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        rake db:migrate RAILS_ENV=development
    - name: Testing your branch....
      run: bundle exec rake my_namespace:my_task1
